### PR TITLE
ci: add hacky support for tag parameters

### PR DESCRIPTION
**Pull request by AurelienGasser**
Currently, the CI script only support branches as arguments.

This PR prevents the script from crashing when trying to get the digest of a git tag, with commands like:

```
run-ci.py --substra-tests 0.6.0
```

### CODE REVIEW

**Comment by Kelvin-M** [comment]
You should update argpase helper and run-ci.py too to be more explicit as `branch` var name is used everywhere :D

**Comment by AurelienGasser** [comment]
@Kelvin-M I'd rather not complicate things too much and keep "branch" everywhere. I don't want to add full support for tags at this point, just to unblock @jmorel. I'll update the PR name/description accordingly.

**Comment by Kelvin-M** [comment]
Is it still relevant ?

**Comment by jmorel** [comment]
I don't have a need for it anymore myself, but maybe a check with other contributors would be a good idea.

**Review by Kelvin-M — APPROVED** [review]

**Review by Kelvin-M — APPROVED** [review]

**Pull request merged**
